### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by Korijn**
Partly addresses #12 

Note: I can't run the codegen-script since I don't have a binary yet. I tried adjusting it to produce noqa comments but I can't verify if it works properly. It probably fails to do so because it is used in conjunction with black, so we can't tell on which lines the violations will end up

Either way, this PR:

* Configures flake8 to be compatible with black (according to their docs)
* Fixes flake8 violations (a few)
* Adds specific error ignores to lines I couldn't/didn't know how to fix (a lot)
* Runs flake8 in CI
* Also runs black on python files in the root of the repo on CI
* Removed existing `# noqa` that didn't trigger violations

---

I'm unsure of the following changes:

```python
from py2spirv import python2spirv, i32, vec2, vec3, vec4
```
Is that how it's supposed to be done?

### CODE REVIEW

**Comment by almarklein** [comment]
> I can't run the codegen-script since I don't have a binary yet.

It does not load the binary :)  Also, the files it generates are blackified before writing, so I'm curious what noqa's were needed.

Will have a proper look at this after xmas :)

**Comment by Korijn** [comment]
> It does not load the binary :)

Really! Doh. I should have just tried it.

> Also, the files it generates are blackified before writing, so I'm curious what noqa's were needed.

Black doesn't fix comments that exceed max line length, for example. Also, the undefined type hints.

**Comment by almarklein** [comment]
> Black doesn't fix comments that exceed max line length, for example. Also, the undefined type hints.

Maybe we should simply disable line length checking on flake8.

**Comment by Korijn** [comment]
I would be ok with disabling that check!

**Pull request merged**
