### PR TITLE
Improve api coverage

### LINKED ISSUE #12: Tests ... we need tests
Let's start with flake checks, btw.

### PR DESCRIPTION
**Pull request by almarklein**
This brings us so close to full coverage that I consider this closing #10. Also closes #12. Now uncovered features are:

* debug markers (because I have no idea yet how these work)
* render bundles (because wgpu-native does not support them (yet))
* indirect drawing
* ~a few missing features inside render calls: depth_stencil_state, resolve_target, depth_stencil_attachment~ implemented and covered with tests!

todo:
* [x] test coverage!

### CODE REVIEW

**Comment by Korijn** [comment]
I dont see debug markers in the webgpu spec... Can you provide a link/reference so I can read up on them?

**Comment by Korijn** [comment]
Would it be much effort to add the indirect drawing API? It seems like it would be necessary to support instanced rendering?

**Comment by almarklein** [comment]
> I dont see debug markers in the webgpu spec...

E.g. [here](https://gpuweb.github.io/gpuweb/#dom-gpucommandencoder-insertdebugmarker). Not much info though. More [here](https://www.khronos.org/opengl/wiki/Debugging_Tools).

> Would it be much effort to add the indirect drawing API?

I'll have a look. I initially planned to just implement all features that we might need in visvis2. But yeah ... we're pretty close to 100% now so maybe  just push through.

> It seems like it would be necessary to support instanced rendering?

I don't think so.

**Comment by Korijn** [comment]
https://www.khronos.org/opengl/wiki/Debug_Output

This page describes use of debug markers in more detail; apparently you can annotate your GPU commands with "markers" and have the annotations show up in traces/logs, to help you identify/locate things.

**Comment by Korijn** [comment]
> > It seems like it would be necessary to support instanced rendering?
> 
> I don't think so.

OK then. Nevermind :)

**Comment by almarklein** [comment]
afbeelding

**Comment by almarklein** [comment]
I'm merging this. I will have a go at debug markers and indirect drawing in new PR's.

**Pull request merged**
